- include: check_kubelet.yml

- name: Desired kubernetes state
  set_fact:
    install_k8s: "{{ k8s_state is not defined or k8s_state|lower == 'install' }}"

- name: Install kubernetest on node
  include_tasks: install_kubernetes.yml
  when: install_k8s and not kubelet_service.exists
  register: k8s_install_res

- name: Join node
  become: yes
  become_method: runas
  become_user: SYSTEM
  win_shell: |
    {{k8s_join_command}}
  when: install_k8s and kubelet_service.exists and k8s_join_command is defined and k8s_install_res.rc is defined and k8s_install_res.rc == 0

- name: Uninstall kubernetest on node
  include_tasks: uninstall_kubernetes.yml
  when: not install_k8s
